services:
  development-rw_front:
    container_name: development-rw_front
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env
    ports:
      - 5173:5173
    working_dir: /usr/src/front
    volumes:
      - .:/usr/src/front
    networks:
      - development-rw_network

networks:
  development-rw_network:
    external: true
