services:
  rw_front:
    container_name: rw_front
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5173:5173
    working_dir: /usr/src/front
    volumes:
      - .:/usr/src/front
    networks:
      - 01-bancodedados_default

networks:
  01-bancodedados_default:
    external: true
